version: '2.0'
services: 
    web:
        build:
            context: .
            dockerfile: "recore.web/Dockerfile"
        ports:
            - "80:8080"
        links:
            - postgres
        environment: 
            - recore__connectionstring=Host=postgres; Port=5432; User Id=reuben; Password=password; Database=recore;
    postgres:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=reuben
            - POSTGRES_DB=recore